# Generated by Django 4.2.25 on 2025-10-30 23:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('surname', models.CharField(max_length=100)),
                ('dadname', models.CharField(max_length=100)),
                ('issue_date', models.DateField()),
                ('number', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='VaccinationCertificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vaccination_date', models.DateField()),
                ('vaccine_type', models.CharField(max_length=100)),
                ('comments', models.TextField(blank=True)),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sert.medicalpolicy')),
            ],
        ),
    ]
